#!/bin/bash
#this is a test script
#created by serge or email or useror user id
#date :sept 2023
#Modified on nov 2020 by EE



echo "hello world"
echo "Welcome to our store.We have sale on ailes 13"
